### ISSUE TITLE
Fix login system

### ISSUE THREAD

**Issue by ArthurSaprunov** [Renzie/Verkeersquiz-Puurs#10]
The login system still need to be fixed. 
No redirect to the login page on the dashboard.

**Comment by ArthurSaprunov** [comment]
We could use the dirty way:

`<?php echo "<script> window.location.replace('login.php') </script>" ?>`

This will work for the redirect but I'm not sure about the resetting the session.

**Comment by MaximeMylle** [comment]
redirect to logout.php should fix the session issue

**Comment by MaximeMylle** [comment]
done ( i guess )
