### ISSUE TITLE
Log the login attemps

### ISSUE THREAD

**Issue by Skydragonsz** [Renzie/Verkeersquiz-Puurs#15]
Log from where they try and login, if this IP is used multiple times, block it.

[Getting IP from the server](https://stackoverflow.com/questions/3003145/how-to-get-the-client-ip-address-in-php)

This wil make #10 more secure!

**Comment by ArthurSaprunov** [comment]
f87586b9f280b1c932c678d194258a31d4561494 only logs the attempts but doesn't block them yet
