### ISSUE TITLE
Refactor database

### ISSUE THREAD

**Issue by Skydragonsz** [Renzie/Verkeersquiz-Puurs#18]
The database needs to be refactored!!! 

Template: We need to store all the data in tables, not a JSON in a field! (This will make the code for the side harder but this is needed)

#17 Few typos that we also need to fix.

#16 This should be easy to fix with the database options.

Clean the database for the live version.

**Comment by ArthurSaprunov** [comment]
The database if a bit refactored but not everything (8d8b0512e8aedb1292b4e2350180bd47223d5eff)
This should be done later!
